name: Build LaTeX document

on:
  push:
    branches: [master, main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile french LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume_fr.tex
      - name: Compile english LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume_en.tex
      - name: Update Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: Resume
          files: |
            resume_fr.pdf
            resume_en.pdf
